name: Pulumi Deploy

on:
  push:
    branches:
      - main



jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Pulumi
      uses: pulumi/action-install-pulumi-cli@v1
    - name: Pulumi login
      run: pulumi login
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    - name: Install Node.js (if using Node.js in Pulumi)
      uses: actions/setup-node@v1
      with:
        node-version: '14'
        
    - name: Select Pulumi stack
      run: pulumi stack select <stack-name> --create
      working-directory: pulumi

    - name: Run Pulumi up
      run: pulumi up --yes
      working-directory: pulumi
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}